### Create Prescription
POST http://localhost:5000/api/prescriptions
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NTAzNzQ5NmExNTc5NjUyNjk2ODI1NyIsImlhdCI6MTczMzMxMDI4MSwiZXhwIjoxNzM1OTAyMjgxfQ.HdCrILiR1rieALWfs5C6fod3S11CFZ1D8D_H4ac6n3k
Content-Type: application/json

{
    "patient_id": "6753668162ae38bdf7368784",
    "doctor_id": "675433f5caf1c6a1dd2cdc3c",
    "appointment_id": "675555f1721ec2218e4337fa",
    "medications": [
        {
            "name": "Amoxicillin",
            "dosage": "10mg",
            "frequency": "Twice daily",
            "duration": "7"
        }
    ],
    "instructions": "Take after meals"
}


### Get Prescription by ID
GET http://localhost:5000/api/prescriptions/patient/6750af7e6dd96e12b38b5e93
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NTAzYjIxMDhmYmM3Y2NjYzIxMjFjYiIsImlhdCI6MTczMzU3NTMwOCwiZXhwIjoxNzM2MTY3MzA4fQ.9sDcvNCuDW0B8q9IjCzZnUs_SytkjoTxDBlWCakSEHQ