apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: my-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: fatimarathore2018/backend_hospital_management_system:latest
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URI
          value: mongodb://mongo:27017/OasisHospitalManagementSystem
        - name: PORT
          value: "5000"
        envFrom:
        - secretRef:
            name: backend-secrets
