apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: scd-namespace
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
