name: Build and Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set Docker environment for Minikube
      shell: powershell
      run: |
        Write-Host "Setting Docker environment to Minikube's Docker daemon manually..."
        $envVars = & "C:\Program Files\Kubernetes\Minikube\minikube.exe" docker-env --shell powershell
        foreach ($line in $envVars) {
          if ($line -match '^\$Env:([^=]+)\s*=\s*"([^"]+)"') {
            $key = $matches[1]
            $value = $matches[2]
            Write-Host "Setting $key..."
            [System.Environment]::SetEnvironmentVariable($key, $value, "Process")
          }
        }

    - name: Build backend image
      shell: powershell
      run: docker build -t musfirah1/hms_backend:latest ./backend

    - name: Build frontend image
      shell: powershell
      run: docker build -t musfirah1/hms_frontend:latest ./frontend

    - name: Login to Docker Hub
      shell: powershell
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push backend image
      shell: powershell
      run: docker push musfirah1/hms_backend:latest

    - name: Push frontend image
      shell: powershell
      run: docker push musfirah1/hms_frontend:latest

    - name: Deploy to Minikube
      shell: powershell
      run: |
        kubectl apply -f k8s/mongo-deployment.yaml
        kubectl apply -f k8s/mongo-service.yaml
        kubectl apply -f k8s/backend-deployment.yaml
        kubectl apply -f k8s/backend-service.yaml
        kubectl apply -f k8s/frontend-deployment.yaml
        kubectl apply -f k8s/frontend-service.yaml
