name: Build and Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker to use Minikube's Docker daemon
      run: |
        echo "Switching Docker to use Minikube's environment..."
        eval $(minikube docker-env)

    - name: Build backend image
      run: docker build -t musfirah1/hms_backend:latest ./backend

    - name: Build frontend image
      run: docker build -t musfirah1/hms_frontend:latest ./frontend

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push backend image
      run: docker push musfirah1/hms_backend:latest

    - name: Push frontend image
      run: docker push musfirah1/hms_frontend:latest

    - name: Deploy to Minikube
      run: |
        kubectl apply -f k8s/backend-deployment.yaml
        kubectl apply -f k8s/backend-service.yaml
        kubectl apply -f k8s/frontend-deployment.yaml
        kubectl apply -f k8s/frontend-service.yaml
        kubectl apply -f k8s/mongo-deployment.yaml
        kubectl apply -f k8s/mongo-service.yaml
